on:
  pull_request:
    branches:
      - master
      - develop
      - feature/**
    paths:
      - pubspec.yaml
      - pubspec.lock
      - lib/**/*.dart
      - test/**/*.dart
      - web/**
      - android/**
      - ios/**
      - windows/**
      - linux/**
      - macos/**

jobs:
  report:
    name: ğŸ“ Test report
    runs-on: ubuntu-latest
    steps:
      - name: Test report
        uses: dorny/test-reporter@v1
        with:
          artifact: test-results
          name: Test Report
          path: "**/tests.json"
          reporter: flutter-json
          fail-on-error: "false"